### ISSUE TITLE
Invalid repo content due to push mistake?

### ISSUE THREAD

**Issue by HiDeoo** [astro-community/md#12]
It looks like the content of this repo was replaced by the one from https://github.com/astro-community/context with this [commit](https://github.com/astro-community/md/commit/567b6cef2c715ed82b7bbd1ee2869b26d11d9f3e) which I assume was not meant for this repo?

**Comment by jonathantneal** [comment]
Thanks! I’m not sure how that happened, but thanks for letting me know. I’ve fixed it.
