### ISSUE TITLE
Abysmally slow build - not caching createMarkdownProcessor

### ISSUE THREAD

**Issue by oliwarner** [astro-community/md#16]
Each time I use `<Markdown of={string} />` the page build appears to be extended by about 200-400ms (from 5ms). In practice this means some pages take multiple seconds to build. I'm not going to be able to deploy like this. I've disabled all custom markdown config, stripped everything right back, but it's still adding a massive overhead.

Looking at the md source, every `<Markdown.../>` tag, every `markdown()` call  builds its own processor via `createMarkdownProcessor()`. It's passing in fresh options each time. I haven't profiled it, but this seems like a really expensive operation given the options are always the same, right?

My reading of the [main Astro markdown build process](https://github.com/withastro/astro/blob/main/packages/astro/src/vite-plugin-markdown/index.ts) is that one instance of the processor gets used for multiple files. I'm not certain how Vite does its magic so I could be wrong.

Either which way, it seems likely this library should be caching and reusing a single processor, or one per set of options if there are multiple options being used.

**Comment by oliwarner** [comment]
Yeah, moving to a single createMarkdownProcessor call speeds things up tremendously. The first page takes a 200-400ms hit, the remaining all complete at full speed. The cost of this is losing per-call options which —for me— seems worth it but it's not my choice.

```
import { createMarkdownProcessor } from '@astrojs/markdown-remark'
import { shared } from './shared.js'
import { HTMLString } from './html-string.js'

const processor = await createMarkdownProcessor({
	...shared.markdownConfig,
})

export async function markdown(
	/** @type {string} */ content,
	/** @type {MarkdownRenderingOptions} */ options = null
) {
	const result = await processor.render(content);
	return new HTMLString(result.code);
}

markdown.inline = async function inlinemarkdown(
	/** @type {string} */ content,
	/** @type {MarkdownRenderingOptions} */ options = null
) {
	const result = await processor.render(content);

	return new HTMLString(
		result.code.indexOf("<p>") === 0 &&
		result.code.indexOf("</p>") === result.code.length - 4
			? result.code.slice(3, -4)
			: result.code,
	);
};

/** @typedef {import('./markdown').MarkdownRenderingOptions} MarkdownRenderingOptions */
```

**Comment by BadMannersXYZ** [comment]
As a palliative fix, I have `markdown: { syntaxHighlight: false }` in my Astro config to avoid most of the performance hit from this. I can't wait for the next release of this library to remove the hacky solution!
