### ISSUE TITLE
Missing peerDependency: @astrojs/markdown-remark

### ISSUE THREAD

**Issue by jbutz** [astro-community/md#2]
The package appears to be missing `@astrojs/markdown-remark` as a peer dependency. In my project, I use NPM workspaces, and with how the packages get resolved it's important peer dependencies are specified.

In my setup `@astropub/md` is installed to `/node_modules/` while `@astrojs/markdown-remark` is being installed to `/packages/astro/node_modules`. With peer dependencies specified that shouldn't be an issue anymore.

**Comment by jonathantneal** [comment]
It should be listed as a peer dependency, at least as of v1.0.0.

https://github.com/astro-community/md/blob/1.0.0/packages/md/package.json#L27-L29
