### ISSUE TITLE
What is the rule of id generation that I need to use anchor jump

### ISSUE THREAD

**Issue by zard999** [astro-community/md#4]
<img width="972" alt="image" src="https://user-images.githubusercontent.com/72585835/226292251-23b41036-83d5-4b51-96c4-7113e0f72c5c.png">

**Comment by jonathantneal** [comment]
This plugin does not generate these tags. You would need to check the documentation for whichever plugin you are using to generate these IDs.

Very likely, it is [github-slugger](https://www.npmjs.com/package/github-slugger).
