### ISSUE TITLE
conditionally disable astro markdown config

### ISSUE THREAD

**Issue by changethe** [astro-community/md#6]
not sure if this is a common need, but I would have a use case for it.

In 99% of cases I want to use my astro markdown plugins etc. but every now and then I need to render a small markdown string without my additional plugins.

Something like config="false" or similar would be a great option to conditionally revert back to the basic markdown renderer without the custom plugins/extensions.

**Comment by jonathantneal** [comment]
I’m open to a PR, but otherwise this is meant to match the built-in functionality of Astro.
