### ISSUE TITLE
Does not work with Astro v3.0

### ISSUE THREAD

**Issue by edmundmiller** [astro-community/md#7]
Getting this error
```js
 error   Package subpath './server/render/index.js' is not defined by "exports" in /home/emiller/src/nf-core/website/node_modules/astro/package.json imported from /home/emiller/src/nf-core/website/node_modules/@astropub/md/lib/component.js
```

**Comment by xexiu** [comment]
Im getting the same error as @Emiller88 with the latest version of astro! :(

**Comment by dinfer** [comment]
same here

**Comment by luwes** [comment]
there was a fix merged but not released to NPM it seems. 
try this `yarn add 'https://gitpkg.now.sh/astro-community/md/packages/md?124d0f2'`

**Comment by jonathantneal** [comment]
Thank you for the reminder. I’ve been going thru some personal disruptions. I’m sorry about this. Now v0.3.0 has been published with this fix.

**Comment by mashehu** [comment]
Works now again.
